sudo: required
language: node_js
node_js:
  - "6.9.1"
  - "7.3.0"
  - "7.4.0"
cache:
  yarn: true
before_install:
  - npm i -g lerna
  - npm i -g babel
  - npm i -g gulp
  - npm i -g mocha
  - npm i -g chai
  - npm i -g yarn
install:
  - lerna bootstrap
  - yarn install
after_success: npm run coverage
